### ISSUE TITLE
Can't use Circle Pad/C-Stick

### ISSUE THREAD

**Issue by LeoMassaFM** [blitzdotcs/Unity3DS#2]
Whenever I try to implement GamePad.CirclePad.x/y into my script, Unity throws an error saying "MissingMethodException"
This also happens when I try implementing the line "UnityEngine.N3DS.Keyboard.SetType(N3dsKeyboardType.Qwerty);" at Start()
WTF???

**Comment by blitzdotcs** [comment]
Could you show a screenshot of the editor and your code?

**Comment by LeoMassaFM** [comment]
![image](https://github.com/blitzdotcs/Unity3DS/assets/95929546/48b78a4d-919e-4028-86d4-a8c191d4ab68)

**Comment by blitzdotcs** [comment]
try removing the"UnityEngine.N3DS." part in the void Start()

**Comment by LeoMassaFM** [comment]
![image](https://github.com/blitzdotcs/Unity3DS/assets/95929546/1f6748fa-e3fe-4a1b-aed4-20d846b33dd2)
![image](https://github.com/blitzdotcs/Unity3DS/assets/95929546/8a949da0-bc62-484f-908d-e409ddd2fa21)
In the second image, the second error appearing when I tried clicking the pause button to unpause.

**Comment by blitzdotcs** [comment]
there might be sum wrong with ur sdk then, reinstall it

**Comment by LeoMassaFM** [comment]
Speaking of which, in order to reinstall I completely wiped out everything related to Unity and the SDK. Then I downloaded the zip file from the link in the readme/main page. I extract the contents and it's all fine and dandy. Except, when I tried to run NDI.exe, it just closed itself a second later. I'll try to install the ARMCC license from an older archive that has it, and see if that changes anything.

**Comment by LeoMassaFM** [comment]
Nope. Something's definetely wrong with the zip from the download page. Because using an older version (1.3.0) works flawlessly. Here's a picture of me trying to install the new package:
![image](https://github.com/blitzdotcs/Unity3DS/assets/95929546/359a5f4d-a1ff-47c7-be17-a92f90c62cb3)

**Comment by blitzdotcs** [comment]
There can't be sum wrong with it cuz my friend literally used the archive.org one to install it 😭

**Comment by LeoMassaFM** [comment]
But then how do I fix the issue in the screenshot above? I downloaded it from the archive.org link in the readme

**Comment by blitzdotcs** [comment]
I dunno never encountered it myself
