### ISSUE TITLE
NDI.exe not opening

### ISSUE THREAD

**Issue by LeoMassaFM** [blitzdotcs/Unity3DS#3]
I downloaded the SDK from the link, and tried opening the NDI.exe file. But when I did, it just showed the Nintendo Developer Interface logo for a second before immediately closing itself. I previously wiped out from my PC anything related to Unity or Nintendo. Do I need the ARMCC license? What am I missing?

**Comment by LeoMassaFM** [comment]
Any news?

**Comment by blitzdotcs** [comment]
Gonna be honest. I completely forgot 💀. I'll try to whenever I can though, school's being a bitch this week

**Comment by blitzdotcs** [comment]
Update: After months I did try reinstall it and shits and it worked for me soo idk why it ain't workin for you
